### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by benoitc** [aeternity/enoise#3]
Would it be possible to have a release available on hex.pm? Or are some features missing for a full release?

**Comment by hanssv** [comment]
I think it should be usable in its current state. I've planned to tag a version that we will use for Aeternity MainNet, which is scheduled soon(TM) :-) No reason really why that can't also be available at hex.pm

**Comment by hanssv** [comment]
Should be available as version 1.0.0 at hex.pm now!

**Comment by benoitc** [comment]
thanks!
